name: My Workflow
on: 
  push:
    branches: #[ master ]
      - "Feature*" 
    #paths:
    #- '**.md'
  #pull_request:
    #branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          include: "test/hello.txt"
          find: "hello"
          replace: "have"
        
      - name: Check outputs and modified files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "test/hello.txt"
          git push   
          
       
      
          
            
      
      
          
