# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: String Replace
      # You may pin to the exact commit or the version.
      # uses: bejoistic/str-replace@efbbb67d349eaf509144d4ce1202ed0c6fb3e340
        uses: bejoistic/str-replace@v1.0.2
        with:
          # A regular expression of files to include in our find and replace
          include: "test.txt" # optional, default is .*
          # A regular expression of files to exclude in our find and replace
          #exclude: # optional, default is .git
          # The string we want to replace
          find: "hello" 
          # The new string to replace with
          replace: "world" 
